package fhtw.quattuor.common.net;

public enum NetType {
    LOGIN,
    LOGIN_FAIL_USERNAME,
    LOGIN_FAIL_PASSWORD,
    LOGIN_SUCCESS,
    LOGOUT,
    LOGOUT_SUCCESS,
    REGISTER,
    REGISTER_FAIL,
    REGISTER_SUCCESS,
    PLAYER_UPDATE,
    PLAYER_UPDATE_FAIL,
    PLAYER_UPDATE_SUCCESS,
    NOT_LOGGED_IN,
    GET_ALL_SESSIONS,
    SET_ALL_SESSIONS,
    CREATE_SESSION,
    SESSION_UPDATE,
    SESSION_UPDATE_REQUEST,
    ONLINE_LIST,
    PRESENCE_UPDATE,
    HIGHSCORE_LIST,
    HIGHSCORE_REQUEST,
    UPDATE_COMP_LEVELS,
    FORBIDDEN,
    ERROR
}
